# Unit-экономика {-}

## Запись занятия {-}

<iframe width="560" height="315" src="https://www.youtube.com/embed/M5Bt4pvNSKI?si=Q3xeTD3JGHcR9-OH" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>

## Unit-экономика

### Что это и зачем

Юнит-экономика – определение числа юнитов масштабирования, маржинальная прибыль от которых необходима для покрытия постоянных издержек и выхода на заданный уровень прибыли. 

Основная идея юнит-экономики простая: Прибыль = маржинальная прибыль – постоянные расходы. Главное, как формируется маржинальная прибыль -- количество клиентов, расходы на привлечение и удержание, 

Юнит-экономику можно считать как до запуска нового предприятия, так и после. Например, если мы хотим запустить стартап, то расписанная юнит-экономика стартапа нужна инвесторам, чтобы понимать за счет чего и когда будут окупаться вложения, насколько вообще жизнеспособна идея.

Точно также юнит-экономику можно считать в уже существующем бизнесе, чтобы определить возможные зоны роста и слабые места.

Стоит помнить, что расписанная юнит-экономика проекта --- это всего лишь модель. А реализуют ее люди, и многие вещи будут зависеть не от модели или рынка, а от команды проекта.


### Юниты масштабирования

Юнитом масштабирования может быть что угодно -- одна сделка, одна продажа, один заказчик или подписчик. Юниты принято выбирать в соответствии с целями компании: что конкретно мы собираемся масштабировать. Юниты могут иметь разную иерархию, на примере пиццерии: заказ > клиент > пиццерия > город > страна. Точно также в рамках одной (крупной) компании может быть несколько разных юнитов.

Сложностью юнита масштабирования добавляет новые метрики в формулы окупаемости и, в целом, рычагов ее изменеяия.
Например, если мы продаем какой-то физический предмет, то нас интересует в первую очередь себестоимость товара. Если наш юнит -- клиент, то мы смотрим на LTV и в модель закладываются расходы на удержание клиента, на повышение среднего чека, и т.д.

Продуктовые аналитики обычно работают с проектами, где юнит масштабирования -- клиент, именно поэтому наши ключевые метрики -- ARPU, LTV, конверсия в платеж, среднее количество платежей на пользователя и т.д. 

### Основные термины

**Fix Costs (Фиксированные расходы)**: расходы, не зависящие линейно от объема продаж или производства. Например, зарплата
генерального директора или программиста в продуктовой компании.

**Variable Costs (Переменные расходы)**: расходы, непосредственно привязанные к единице товара или услуги. Например, стоимость сырья или доставка. В моделях обычно раскладывается на расходы на привлечение / маркетинг, удержание пользователя (Aquisition costs), себестоимость товара или услуги (COGS) и т.д.  

**COGS (Cost of Goods Sold)**: Себестоимость единицы товара или услуги — стоимость материалов, логистики, оплата работы. В общем виде --- переменные издержки, которые несет бизнес в момент сделки. Наивное правило, с помощью которого можно определить, относятся те или иные расходы к COGS или нет: если ваши расходы равны нулю, если у вас нет сделок, то это COGS, и наоборот – если не равны нулю (например, аренда или заработная плата), то это не COGS.

**First sale COGS (1sCOGS, Начальные расходы)**: Дополнительные переменные издержки, которые несет бизнес в момент самой первой сделки. Сюда же можно отнести расходы на первом этапе запуска проекта (закупка оборудования, пуско-наладочные работы и т. д.).

**Gross Profit (Валовая прибыль)**: разница между ценой товара или услуги и её себестоимостью. Нередко называют просто маржой. Если мы считаем не абсолютные значения (деньги), а долю от выручки, то это маржинальность, Gross Profit Margin. 

**User/Unit (Пользователь)**: базовая сущность, определяет, с чем мы работаем, в общем случае представляет собой человека, который познакомился с продуктом благодаря рекламе.

**User / Lead Acqusition**: количество привлекаемых пользователей. По сути горизонт масштабирования, если юнит масштабирования --- пользователи. 

**Aquisition costs (AC, Расходы на привлечение пользователей)**: расходы на рекламу, маркетинг, промокоды и другие сопутствующие расходы, на препродажи (если есть). AC = User Acquisition × Cost per Acquisition = Buyer × Customer Acquisition Cost

**CAC (Customer Acquisition Cost, Стоимость привлечения пользователя)**: расходы на привлечение одного платящего пользователя. То есть пользователя, который купил товар или услугу.   

**Cost per Acquisition (CPA, Расходы на привлечение пользователя)**: стоимость привлечения пользователя, независимо, сделал он платеж или нет. В наиболее общем виде --- стоимость маркетинговых затрат на юнит масштабирования. Наиболее характерные метрики: Cost per Install (CPI), Cost per Action (CPS), Cost per Lead (CPL).  Сюда же можно отнести промежуточные метрики рекламных кампаний: Cost per Mile (CPM, цена за тысячу показов рекламы), CPC (Cost per Click, цена за количество кликов по рекламе) и прочие. 

**Conversion to first purchase (C1, Конверсия в первую покупку)**: какой процент привлеченных юнитов масштабирования становится клиентами. Одна из ключевых метрик продукта, определяет, насколько хорошо продукт продает ценность.

**Buyer/Customer (B, клиент / пользователь)**: число клиентов, которых компания получает от потока пользователей с учетом имеющегося коэффициента конверсии. то есть это тот user / unit, который сделал покупку или воспользовался услугой. B = UA × C1.

**Average Payment Count (APC)**: Среднее число платежей, приходящееся на одного клиента. APC = Количество платежей / Buyer. Правда, надо учитывать интервал, за который сделаны платежи.

**Average Order Value (AOV или Av. Price, Средний чек)**:  сумма, которую в среднем платят клиенты за товары или услуги.

**Customer Lifetime Value (CLTV)**: доход на одного платящего пользователя (клиента). Нюанс в том, что мы обычно не знаем, за какой период берутся платежи пользователя. Максимальный период -- Lifetime, но в практике обычно берут 90/180/350 и более дней, в зависимости от бизнеса. CLTV = (Av. Price – COGS) × APC – 1sCOGS


**Contribution Margin (CM, Маржинальная прибыль)**: разница между тем, сколько мы получили от продажи товаров/услуг привлеченным пользователям и стоимостью привлечения пользователей. Можно выразть как Gross Profit - Acquisition Cost.  Для достижения точки безубыточности маржинальная прибыль должна покрывать постоянные издержки. При положительном значении маржинальной прибыли говорят, что юнит-экономика сходится. А положительную разницу между маржинальной прибылью и постоянными издержками можно принять за EBITDA.

### Пример
Общая идея бизнеса: покупаем стулья в Китае, привозим в Россию и продаем дистрибьютору.
Предположим, продаем мы один стул за 1000 рублей (Av. Price).
При этом наши переменные расходы (COGS) на единицу товара:

 - 60 рублей налог (6% с оборота)
 - 250 рублей закупка
 - 100 рублей растаможка
 - 150 рублей логистика
 - 100 рублей брак (вероятность 10%)
 - 40 рублей остальное 

Рекламы у нас нет, так как мы продаем стулья дистрибьютору. Поэтому Acquisition cost = 0.

В результате с каждого стула у нас маржа (Gross Profit) 300 рублей. При этом мы не учитываем постоянные расходы на зарплату и аренду офиса/склада. 

Таким образом за 100 стульев мы получим 30000 рублей. Если вычесть постоянные расходы, то, скорее всего, мы будем в убытке. Однако если мы решим привезти 10000 стульев, то маржа вырастет, а переменные расходы останутся теми же. И мы, возможно, выйдем в прибыль.

### Шаблоны расчета

Рекомендую поизучать [шаблоны](https://docs.google.com/spreadsheets/d/1xoMoAh2JaZcQCTBn_dmrpOnTwFu8XPCzYIXD23gKrvM/edit#gid=631121018) расчета юнит-экономики Ильи Красинского. Это один евангелистов юнит-экономики в ру-сегменте. У него достаточно подробный набор метрик, как общих, так и на пользователя.

Точно также есть другие шаблоны, тысячи их:

- [Шаблон юнит-экономики Яндекс Практикум](https://docs.google.com/spreadsheets/d/1pexEadMuCYgbklIpYC3jlzELX5hJ3y0cBwihyH8lbpA/edit#gid=0)
- [Шаблон расчета юнит экономики (Skillbox)
](https://docs.google.com/spreadsheets/d/1vlixZmvDQsMn9AkN4qoe56JgsXKDyF9O/edit#gid=1722210460)
- [Симулятор](https://utmstat.com/startup) стартапа

### Unit-экономика для аналитиков

Юнит-экономика -- в первую очередь инструмент для оценки бизнеса, поиска его узких точек и возможностей масштабирования.
Продуктовые аналитики касаются только небольшой ее части --- в первую очередь того, что касается поведения пользователя (то, как он платит, за что платит, как долго пользуется, как возвращается, как удерживается и т. д.), во вторую очередь --- затраты на привлечение пользователя. И то в общем виде, сколько потратили на привлечение, так как более тонкими деталями типа CTR, IR, спецификой каналов привлечения, маркетинговой атрибуцией и т. д. занимаются больше маркетинговые аналитики. Постоянный расходы типа оплаты аренды офиса, ФОТ, налоги, прочие расходы и доходы, не связанные конкретно с клиентами/пользователями обычно остаются не в фокусе или вообще за пределами задач продуктовых аналитиков.

Собственно, задача продуктовых аналитиков --- тем или иным способом увеличить деньги от пользователя и таким образом повысить маржинальную прибыль и/или окупаемость. 

## Дополнительные материалы

- [учебник](https://khanin.info/book) Д.Ханина по юнит-экономике.
- [видео-курс](https://www.youtube.com/playlist?list=PLrxwUD4VIMOOopm4AT8ysnhTQJERQqSJD) Д.Ханина по юнит-экономике
- платный [курс](https://unit.startupoftheday.ru/) А.Горного "Unit-экономика от А до Я"
- [конспект](https://practicum.yandex.ru/blog/chto-takoe-yunit-ekonomika-kak-schitat/) по юнит-экономике от Я.Практикума
- неплохая [инфографика](https://vc.ru/money/61504-vsya-yunit-ekonomika-v-odnoy-infografike) по юнит-экономике
- неплохая [статья](https://kontur.ru/compass/spravka-compass/22581-yunit_ekonomika_kak_eyo_rasschitat_i_ocenit_uspeshnost_biznesa) в блоке Контур.Компас




